language: python
python:
  - "3.6"
  - "3.7"
install: true
script: true
deploy:
  provider: pypi
  user: maroshmka
  password:
    secure: "UIboahPJw8gHYKOXs5LMDjSNONC2eMBAq6gDAobVrkoh/2+qoo1pspItEdL/Bxt77gH22ltEZK0FEmXtpFqmtuuf5Iaf3auPh+q+uYRSjpiaRqR+zhvLQ1Tr9lfPRmw2HUWnmJVknYomG385sYu+BZeZExQ2eGUcUhqo3mt6eabWegy9K0Clp1MiJh6YolzUbU9FRnkdFyuneto8+rFPeLfGBNluYaLSW6x1dNt3Z8ppNb+QrOs0P9TG17ccKJRD7/4yw6ZuWFagT/OfjNiUMJzh4Su+IjBxTaMYIVKVNOLcK1G75YSw0Gbq1rmu7xi5OBdrGXMEFAk/4ydtoU+kfYGbZkVDcu6PvNGNaOAHNZOpw8UEmvfZ0LJytpvZub4zL0g44CDVRs/tWzFHkt8uQptqid4N1xA6AufXLshqbK1eaYMmhPkV81kTPqeHiVaWdUM0u8MHaqCoMAaYc0cWQc2UIpLWt6MTE1HcFEh4rfxK/3M1G5nTns34wzU6TfrTFgAKTumjhOVh3YISujR89NOAqSAc3tXJiSPx/ib84PkUD1TKFpFcA2pEeqUezFmGNKg8n+VJYlpL48UFZxhOdWtcCJPzoeSjNjQIcjcX95cCKE/2hPCEHqdNSB0BnO1CT+671QvKETeNe53TU8lZF0bBhpeAsUyBY/fjvz0/qCs="
  on:
    tags: true
  distributions: sdist bdist_wheel
